spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/tarzan_cms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    #username: tarzan
    #password: 123456
    platform: h2
    driverClassName: org.h2.Driver
    url:  jdbc:h2:file:${user.home}/.tarzan-cms/db/cms
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
   generate-ddl: false
  redis:
    host: localhost
    port: 6379
    password: 666666
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
server:
  servlet:
    context-path: /

file:
  #上传的文件对外暴露的访问路径
  access-path-pattern: /u/**
  #文件上传目录
  upload-folder: /file/upload/
  #文件预览、下载的访问路径前缀
  access-prefix-url: http://localhost:80/u

static:
  #静态html对外访问路径
  access-path-pattern: /html/**
  #静态html路径
  folder: /tarzanCms/html/path

cms:
  theme-dir: ${user.home}/.tarzan-cms/theme
  backup-dir: ${user.home}/.tarzan-cms/backup
  embedded-redis-enabled: true
  embedded-redis-port: 6379
  embedded-redis-password: 666666