server:
  port: 80
  #tomcat:
   # uri-encoding: utf-8
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 20
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存1
    direct-buffers: true
  max-http-header-size: 1MB
  compression:
    enabled: true
    minResponseSize: 512
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring:
  profiles:
    active: dev
  datasource:
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 10000
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        reset-enable: false
        url-pattern: /druid/*
        allow:
        deny:
      filter:
        wall:
          config:
            multi-statement-allow: true
            comment-allow: true
          enabled: true
      validation-query: select 1
      test-while-idle: true
  thymeleaf:
    cache: false
    mode: HTML
    content-type: text/html
    prefix: file:${user.home}/.tarzan-cms/
    template-resolver-order: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/**/*.xml,mapper/*.xml
  type-aliases-package: com.tarzan.**.model

